branch-protection:
  orgs:
    cb-kubecd:
      repos:
        environment-shriekviolet-dev:
          protect: true
          required_status_checks:
            contexts:
            - integration
  protect-tested-repos: true
deck:
  spyglass: {}
gerrit: {}
owners_dir_blacklist:
  default: null
  repos: null
plank: {}
postsubmits:
  cb-kubecd/environment-shriekviolet-dev:
  - agent: tekton
    branches:
    - master
    context: ""
    name: release
presubmits:
  cb-kubecd/environment-shriekviolet-dev:
  - agent: tekton
    always_run: true
    context: integration
    name: integration
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(\s+|$)
push_gateway: {}
sinker: {}
tide:
  context_options:
    from-branch-protection: true
    required-if-present-contexts: null
    skip-unknown-contexts: false
  queries:
  - labels:
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
    repos:
    - cb-kubecd/environment-shriekviolet-dev
